version: "3"

services:
  pac-zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "22181:2181"

  pac-kafka:
    image: confluentinc/cp-kafka:7.3.3
    hostname: pac-kafka
    container_name: pac-kafka
    depends_on:
      - pac-zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "pac-zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://pac-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  pac-kafka-ui:
    container_name: pac-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "38080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: pac-kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: pac-zookeeper:2181

  pac-mongo:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: localtest
      MONGO_INITDB_ROOT_PASSWORD: localtest

  pac-redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  pac-mariadb:
    image: mariadb:10.11.2
    ports:
      - "33306:3306"
    environment:
      TZ: Asia/Seoul
    env_file: ./db/env
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:
