### auth-service principal
GET {{pac-web}}/api/v1/auth-service/me
Authorization: Bearer {{access_token}}

> {%
    client.test("auth-service principal", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
        client.assert(response.body.id.trim().length > 0);
    });

    client.global.set("room_owner", response.body.id);
%}

### chat public room list
GET {{pac-web}}/api/v1/room/list?page=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

> {%
    client.global.set("public_room", response.body.content[0].roomId);
    client.log(response.body.content[0].roomId);
%}

### room create
POST {{pac-web}}/api/v1/room
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "roomName": "만들어보기",
  "description": "잘될까",
  "imageUrl": "#",
  "capacity": 10,
  "roomPublic": "AVAILABLE"
}

### chat own room list
GET {{pac-web}}/api/v1/room/own/list?page=1
Authorization: Bearer {{access_token}}
Content-Type: application/json

### retrieve chat room info
GET {{pac-web}}/api/v1/room/{{public_room}}
Authorization: Bearer {{access_token}}

### change chat room info
PUT {{pac-web}}/api/v1/room/{{public_room}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "roomId": "{{public_room}}",
  "name": "변경된 채팅방 이름",
  "roomStatus": "ALIVE",
  "roomPublic": "AVAILABLE",
  "description": "변경된 채팅방 설명",
  "imageUrl": "#",
  "capacity": 312,
  "ownerMemberId": "{{room_owner}}"
}

### join chat room
POST {{pac-web}}/api/v1/room/{{public_room}}/join
Authorization: Bearer {{access_token}}

### exit chat room
POST {{pac-web}}/api/v1/room/{{public_room}}/exit
Authorization: Bearer {{access_token}}

### chat logs
GET {{pac-web}}/api/v1/chat/log/simple/{{public_room}}?page=1
Authorization: Bearer {{access_token}}
