############### auth


### member join test
POST {{pac-web}}/api/v1/auth/join
Content-Type: application/json

{
  "username": "test312",
  "password": "test1",
  "nickname": "이름312",
  "email": "d312@d.com"
}

### login test
POST {{pac-web}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "test312",
  "password": "test1"
}

> {%
    client.test("getTokenFromResponse", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
        client.assert(response.body.token.trim().length > 0);
    });

    // https://youtrack.jetbrains.com/issue/IDEA-239263/Response-handler-add-API-to-get-set-cookies
    client.log(response.body.token);
    client.global.set("access_token", response.body.token);
    client.global.set("room_owner", response.body.id);

%}


### validate web authorization
GET {{pac-web}}/auth/endpoint/check

### logout suthorize
GET {{pac-web}}/logout

### validate session
POST {{pac-web}}/api/v1/auth/validate
Content-Type: application/json

{
  "sessionId" : "{{access_token}}",
  "roomId" : "test"
}


############## chat room

### chat public room list
GET {{pac-web}}/api/v1/room/list?page=1
Content-Type: application/json

> {%
    client.global.set("public_room", response.body.content[0].roomId);
    client.log(response.body.content[0].roomId);
%}

### room create
POST {{pac-web}}/api/v1/room
Content-Type: application/json

{
  "roomName": "만들어보기",
  "description": "잘될까",
  "imageUrl": "#",
  "capacity": 10,
  "roomPublic": "AVAILABLE"
}

### chat public room list
GET {{pac-web}}/api/v1/room/list
Content-Type: application/json

### chat own room list (paging)
GET {{pac-web}}/api/v1/room/own/list?page=2
Content-Type: application/json

{
  "sessionId" : "{{access_token}}"
}

### retrieve chat room info
GET {{pac-web}}/api/v1/room/{{public_room}}

### change chat room info
PUT {{pac-web}}/api/v1/room/{{public_room}}
Content-Type: application/json

{
  "roomId": "{{public_room}}",
  "name": "변경된 채팅방 이름",
  "roomStatus": "ALIVE",
  "roomPublic": "AVAILABLE",
  "description": "변경된 채팅방 설명",
  "imageUrl": "#",
  "capacity": 312,
  "ownerMemberId" : "{{room_owner}}"
}

### exit chat room
POST {{pac-web}}/api/v1/room/{{public_room}}/exit

### join chat room
POST {{pac-web}}/api/v1/room/{{public_room}}/join



######### chat message

### chat logs
GET {{pac-web}}/api/v1/chat/log/simple/7394e567-daab-4d48-81f8-ecc0c482e94e?page=2




### #Cookie: PAC_SESSIONID=NWRiYjY2ZDQtMTk3NC00MjBkLWIxZDItZTU1NTdmMzEyMWQ3;





