plataanywherechat.message.application.host=${PAC_MESSAGE_HOST}
plataanywherechat.message.application.port=${PAC_MESSAGE_PORT}

server.port=${PAC_WEB_PORT}
server.servlet.session.cookie.name=PAC_SESSIONID

# MariaDB
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${PAC_MARIADB_DB}
spring.datasource.username=${PAC_MARIADB_ID}
spring.datasource.password=${PAC_MARIADB_PASSWORD}
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

spring.sql.init.mode=never
spring.sql.init.platform=

spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDB103Dialect

### Spring Security OAuth
spring.security.oauth2.client.registration.github.client-id=${PAC_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${PAC_GITHUB_SECRET}

# Redis
spring.redis.host=${PAC_REDIS_HOST}
spring.redis.port=${PAC_REDIS_PORT}
spring.data.redis.repositories.enabled = false

### Spring Security Session store Redis
spring.session.store-type=redis
spring.main.allow-bean-definition-overriding=true

# MongoDB
spring.data.mongodb.host=${PAC_MONGODB_HOST}
spring.data.mongodb.port=${PAC_MONGODB_PORT}
spring.data.mongodb.database=${PAC_MONGODB_DB}
spring.data.mongodb.username=${PAC_MONGODB_USERNAME}
spring.data.mongodb.password=${PAC_MONGODB_PASSWORD}

