plataanywherechat:
  broker:
    chat:
      message:
        topic: development.pac.chat.message
      push:
        topic: development.pac.chat.push

auth-service:
  jwt:
    secret: ${AUTH_SERVICE_JWT_SECRET:this-is-a-local-auth-service-secret-32-bytes}

server:
  port: 3121

spring:
  main:
    web-application-type: reactive
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: pac_group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pac
      username: localtest
      password: localtest
