plataanywherechat:
  broker:
    chat:
      message:
        topic: ${PAC_KAFKA_MESSAGE_TOPIC}
      push:
        topic: ${PAC_KAFKA_PUSH_TOPIC}

auth-service:
  jwt:
    secret: ${AUTH_SERVICE_JWT_SECRET}

server:
  port: ${PAC_MESSAGE_PORT}

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      host: ${PAC_MONGODB_HOST}
      port: ${PAC_MONGODB_PORT}
      database: ${PAC_MONGODB_DB}
      username: ${PAC_MONGODB_USERNAME}
      password: ${PAC_MONGODB_PASSWORD}
