plataanywherechat:
  web:
    application:
      host: localhost
      port: 3120
  broker:
    chat:
      message:
        topic: development.pac.chat.message
      push:
        topic: development.pac.chat.push

auth-service:
  jwt:
    secret: ${AUTH_SERVICE_JWT_SECRET:this-is-a-local-auth-service-secret-32-bytes}

server:
  port: 3121

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pac
      username: localtest
      password: localtest
