plataanywherechat:
  web:
    application:
      host: localhost
      port: 3120
  broker:
    chat:
      message:
        topic: development.pac.chat.message
      push:
        topic: development.pac.chat.push

server:
  port: 3121
  servlet:
    session:
      cookie:
        name: PAC_SESSIONID

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pac
      username: localtest
      password: localtest
