plataanywherechat:
  web:
    application:
      host: ${PAC_WEB_HOST}
      port: ${PAC_WEB_PORT}
  broker:
    chat:
      message:
        topic: ${PAC_KAFKA_MESSAGE_TOPIC}
      push:
        topic: ${PAC_KAFKA_PUSH_TOPIC}

server:
  port: ${PAC_MESSAGE_PORT}
  servlet:
    session:
      cookie:
        name: PAC_SESSIONID

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      host: ${PAC_MONGODB_HOST}
      port: ${PAC_MONGODB_PORT}
      database: ${PAC_MONGODB_DB}
      username: ${PAC_MONGODB_USERNAME}
      password: ${PAC_MONGODB_PASSWORD}
